### ISSUE TITLE
Write general docs

### ISSUE THREAD

**Issue by LouisDesdoigts** [LouisDesdoigts/dLux#16]

**Comment by LouisDesdoigts** [comment]
@benjaminpope has set up a gh-pages branch for docs https://louisdesdoigts.github.io/dLux/, but I think starting out with this is a good idea, and then we can merge it together cohesively once we have most of it written.

**Comment by Jordan-Dennis** [comment]
Ahhh, I was wondering what the `gh-pages` branch was for. I'll keep writing `docs` on the `Documentation` branch for now then. But move them over long term.

**Comment by Jordan-Dennis** [comment]
Also how do we want to document the `__init__` and `__call__` dunder methods. At the moment I have been documenting both parameter sets just under a `#### Parameters:` label in `Documentation`. This is confusing because it does not specify when to provide the parameters. The other option is to have a `#### Constructor:` heading and then a `#### Parameters:` heading. 
Let me know what you think.

**Comment by Jordan-Dennis** [comment]
Spoke with @benjaminpope and we are using `mkdocs`.

**Comment by Jordan-Dennis** [comment]
Hello again,
Just checking in with an update. The `Wavefront` branch now contains full documentation for the `PhysicalWavefront` class although this has been spread over `Wavefront` and `PlanarWavefront` (name subject to change, I just wanted something more physical). As part of the documenting I have been updating names to match the `PEP 8` style guides. This will be subject to review and will probably require @LouisDesdoigts and I to sit down and review each case individually. Some examples are `get_XXYY` became `get_pixel_grid` and `invertXY` became `invert_x_and_y`. Some probably more annoying ones will be `pixelscale` to `pixel_scale`. @LouisDesdoigts I will probably make a pull request for the `Wavefront` branch into the `GaussianWavefront` branch either today or tomorrow and we can go over these details then. 

Regards

Jordan﻿

**Comment by Jordan-Dennis** [comment]
Hi all,
While I was updating the GitHub issue I thought I would comment on the current state of this. I have set-up the `mkdocs.yml` with the following structure:
```yml
nav:
	- Home: 
	- User Documentation:
		- Optical System: 
		- Layers:
			- Create Wavefront:
			- ect. 
	- Developer Documentation:
		- Propagators:
			- Propagator:
			- Variable Sampling:
				- Variable Sampling Propagator:
				- ect.
			- Fixed Sampling:
				- Fixed Sampling Propagator:
				- ect.
		- Wavefronts:
			- Wavefront:
			- Physical Wavefront:
			- Angular Wavefront:
			- Gaussian Wavefront:
```
These will be available from the GitHub pages by the end of the day and are pending the pull request of the `Propagators` branch.

Regards

Jordan			﻿
